In [24]:
pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (0.25.0)
Requirement already satisfied: scipy>=1.16.3 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (1.18.1)
Requirement already satisfied: numpy>=2.3.5 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (2.5.2)
Requirement already satisfied: pandas>=2.3.3 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (3.0.5)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (3.11.1)
Requirement already satisfied: joblib>=1.5.2 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from mlxtend) (1.6.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from joblib>=1.5.2->mlxtend) (3.1.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (23.2)
Requirement already satisfied: pillow>=9 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.8.2)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from pandas>=2.3.3->mlxtend) (2026.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.25.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.3.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [26]:
data = pd.read_csv(r'C:\Users\Lenovo\Downloads\Documents\Data science\Data_science\data\groceries.csv')
baskets_sets = data.stack().str.get_dummies().groupby(level=0).sum()
baskets_sets_bool = baskets_sets.astype(bool)
apriori( baskets_sets_bool, min_support= 0.02, use_colnames= True)

      support                                           itemsets
0    0.028155                              frozenset({UHT-milk})
1    0.054369                                  frozenset({beef})
2    0.032039                               frozenset({berries})
3    0.027508                             frozenset({beverages})
4    0.072492                          frozenset({bottled beer})
..        ...                                                ...
105  0.022977                frozenset({yogurt, tropical fruit})
106  0.033981        frozenset({whole milk, whipped/sour cream})
107  0.055987                    frozenset({yogurt, whole milk})
108  0.022977  frozenset({other vegetables, whole milk, root ...
109  0.022977  frozenset({yogurt, whole milk, other vegetables})

[110 rows x 2 columns]

In [27]:
df_combo = baskets_sets.astype(bool)
frequent_itemsets = apriori(df_combo,min_support=0.002, use_colnames= True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

       support                                           itemsets  length
0     0.007120                 frozenset({Instant food products})       1
1     0.028155                              frozenset({UHT-milk})       1
2     0.002913                      frozenset({abrasive cleaner})       1
3     0.003560                      frozenset({artif. sweetener})       1
4     0.014887                         frozenset({baking powder})       1
...        ...                                                ...     ...
2313  0.002265  frozenset({whole milk, other vegetables, citru...       5
2314  0.002589  frozenset({whole milk, other vegetables, citru...       5
2315  0.002265  frozenset({whole milk, other vegetables, pip f...       5
2316  0.002265  frozenset({whole milk, tropical fruit, other v...       5
2317  0.002265  frozenset({whole milk, tropical fruit, other v...       5

[2318 rows x 3 columns]

In [28]:
frequent_itemsets[(frequent_itemsets['length']>=3)]

       support                                           itemsets  length
1260  0.002589  frozenset({other vegetables, UHT-milk, bottled...       3
1261  0.002265         frozenset({UHT-milk, bottled water, soda})       3
1262  0.002589  frozenset({other vegetables, whole milk, bakin...       3
1263  0.002265  frozenset({whole milk, whipped/sour cream, bak...       3
1264  0.002589             frozenset({whole milk, berries, beef})       3
...        ...                                                ...     ...
2313  0.002265  frozenset({whole milk, other vegetables, citru...       5
2314  0.002589  frozenset({whole milk, other vegetables, citru...       5
2315  0.002265  frozenset({whole milk, other vegetables, pip f...       5
2316  0.002265  frozenset({whole milk, tropical fruit, other v...       5
2317  0.002265  frozenset({whole milk, tropical fruit, other v...       5

[1058 rows x 3 columns]

In [33]:
rule = association_rules(frequent_itemsets, metric='confidence', min_threshold = 0.9)
rule

                                          antecedents  ... kulczynski
0                   frozenset({hamburger meat, curd})  ...   0.506305
1           frozenset({frozen fish, root vegetables})  ...   0.504414
2         frozenset({yogurt, sausage, bottled water})  ...   0.464708
3           frozenset({sausage, soda, bottled water})  ...   0.466366
4          frozenset({pip fruit, whole milk, butter})  ...   0.462949
5   frozenset({cream cheese , citrus fruit, domest...  ...   0.504414
6   frozenset({whipped/sour cream, curd, tropical ...  ...   0.505675
7   frozenset({other vegetables, pastry, frankfurt...  ...   0.505824
8       frozenset({whole milk, hamburger meat, pork})  ...   0.506723
9     frozenset({yogurt, whole milk, hamburger meat})  ...   0.457563
10  frozenset({yogurt, hard cheese, root vegetables})  ...   0.504414
11     frozenset({other vegetables, pip fruit, pork})  ...   0.460851
12           frozenset({pip fruit, whole milk, pork})  ...   0.462949
13  frozenset({yogurt, specialty cheese, other veg...  ...   0.504414

[14 rows x 14 columns]

In [32]:
rules = association_rules(frequent_itemsets, metric= 'lift', min_threshold= 1)
rules

                             antecedents  ... kulczynski
0          frozenset({other vegetables})  ...   0.164973
1     frozenset({Instant food products})  ...   0.164973
2     frozenset({Instant food products})  ...   0.169385
3           frozenset({root vegetables})  ...   0.169385
4                  frozenset({UHT-milk})  ...   0.143844
...                                  ...  ...        ...
9413             frozenset({whole milk})  ...   0.354414
9414         frozenset({tropical fruit})  ...   0.217396
9415       frozenset({other vegetables})  ...   0.275113
9416                 frozenset({yogurt})  ...   0.299941
9417     frozenset({whipped/sour cream})  ...   0.190625

[9418 rows x 14 columns]

In [34]:
rules[(rules['lift']>= 5) & (rules['confidence'] >= 0.8)]

                                            antecedents  ... kulczynski
7110        frozenset({yogurt, sausage, bottled water})  ...   0.464708
7113          frozenset({sausage, soda, bottled water})  ...   0.466366
7377      frozenset({rolls/buns, sausage, canned beer})  ...   0.451172
8133  frozenset({dessert, whipped/sour cream, other ...  ...   0.453901
8189  frozenset({other vegetables, pastry, frankfurt...  ...   0.505824
8315      frozenset({whole milk, hamburger meat, pork})  ...   0.506723

[6 rows x 14 columns]

In [44]:
fs = apriori(df_combo, min_support= 0.002, use_colnames= True)
fs['length'] = fs['itemsets'].apply(lambda x: len(x))

In [46]:
rules_1= association_rules(fs, metric= 'confidence', min_threshold= 0.9)
rules_1

                                          antecedents  ... kulczynski
0                   frozenset({hamburger meat, curd})  ...   0.506305
1           frozenset({frozen fish, root vegetables})  ...   0.504414
2         frozenset({yogurt, sausage, bottled water})  ...   0.464708
3           frozenset({sausage, soda, bottled water})  ...   0.466366
4          frozenset({pip fruit, whole milk, butter})  ...   0.462949
5   frozenset({cream cheese , citrus fruit, domest...  ...   0.504414
6   frozenset({whipped/sour cream, curd, tropical ...  ...   0.505675
7   frozenset({other vegetables, pastry, frankfurt...  ...   0.505824
8       frozenset({whole milk, hamburger meat, pork})  ...   0.506723
9     frozenset({yogurt, whole milk, hamburger meat})  ...   0.457563
10  frozenset({yogurt, hard cheese, root vegetables})  ...   0.504414
11     frozenset({other vegetables, pip fruit, pork})  ...   0.460851
12           frozenset({pip fruit, whole milk, pork})  ...   0.462949
13  frozenset({yogurt, specialty cheese, other veg...  ...   0.504414

[14 rows x 14 columns]